export class LobbyDO {
  constructor(state, env) {
    this.state = state; this.env = env;
    this.clients = new Map();
    this.rooms = {};
    this.onlinePlayers = {};
    this.pendingRequests = {};
    this.quickQueue = new Set();
  }
  async fetch(request) {
    if (request.headers.get('Upgrade') !== 'websocket') return new Response('WebSocket endpoint', {status:426});
    const pair = new WebSocketPair();
    const [client, server] = Object.values(pair);
    server.accept();
    const id = crypto.randomUUID().replaceAll('-','').slice(0,12).toUpperCase();
    this.clients.set(id, server);
    server.send(JSON.stringify({type:'__id',id}));
    server.addEventListener('message', e => { try { const m=JSON.parse(e.data); this.handle(id,m.event,m.data||{}); } catch(err) { this.send(id,'gameError','پیام نامعتبر'); } });
    server.addEventListener('close', () => this.disconnect(id));
    return new Response(null,{status:101,webSocket:client});
  }
  send(id,event,data){const s=this.clients.get(id); if(s) try{s.send(JSON.stringify({event,data}))}catch(e){}}
  emitAll(event,data){for(const id of this.clients.keys())this.send(id,event,data)}
  emitRoom(roomId,event,data){const r=this.rooms[roomId]; if(!r)return; const ids=new Set([...(r.players||[]).map(p=>p.id),...(r.watchers||[])]); for(const id of ids)this.send(id,event,data)}
  player(id){return this.onlinePlayers[id]}
  roomFor(id){for(const [rid,r] of Object.entries(this.rooms)){if((r.players||[]).some(p=>p.id===id))return {roomId:rid,room:r,role:'player'};if((r.watchers||[]).includes(id))return {roomId:rid,room:r,role:'watcher'}}return null}
  updateList(){this.emitAll('playerListUpdate',Object.values(this.onlinePlayers).map(p=>({id:p.id,name:p.name,status:p.status,socketId:p.id,avatar:p.avatar||'🐔'})))}
  shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  deck(){let d=[];for(let i=0;i<21;i++)d.push('مرغ');for(let i=0;i<21;i++)d.push('خروس');for(let i=0;i<12;i++)d.push('لانه');for(let i=0;i<7;i++)d.push('روباه');for(let i=0;i<3;i++)d.push('تله');for(let i=0;i<2;i++)d.push('مار');return this.shuffle(d)}
  newRoom(a,b){const rid=Math.random().toString(36).slice(2,8).toUpperCase();this.rooms[rid]={host:a.id,players:[a,b].map(p=>({id:p.id,name:p.name,hand:[],eggs:0,chicks:0})),gameStarted:false,deck:this.deck(),eggTokens:18,currentTurn:null,winner:null,discardPile:[],watchers:[]};return rid}
  start(rid){const r=this.rooms[rid];if(!r)return;r.gameStarted=true;r.players.forEach(p=>{for(let i=0;i<4;i++)if(r.deck.length)p.hand.push(r.deck.pop())});r.currentTurn=r.players[0].id;this.emitRoom(rid,'gameStarted',{roomId:rid});this.emitRoom(rid,'gameState',r)}
  broadcast(rid){const r=this.rooms[rid];if(r){this.emitRoom(rid,'gameState',r);this.emitRoom(rid,'roomUpdate',r)}}
  async handle(id,event,d){
    const me=this.player(id);
    if(event==='registerPlayer'){const name=String(d.playerName||'').trim();if(!name)return this.send(id,'registrationError','نام نامعتبر است');const existing=Object.values(this.onlinePlayers).find(p=>p.name===name&&p.id!==id);if(existing)return this.send(id,'registrationError','این نام قبلاً توسط بازیکن دیگری استفاده می‌شود');this.onlinePlayers[id]={id,name,status:'ready',accountId:d.accountId||null,avatar:d.avatar||'🐔'};this.send(id,'registrationSuccess',{id,name});this.updateList();return}
    if(event==='getPlayerList'){return this.updateList()}
    if(event==='loadProfile'){return this.send(id,'profileData',{profile:{username:me?.name||'بازیکن',avatar:me?.avatar||'🐔',gamesPlayed:0,wins:0,losses:0}})}
    if(event==='saveProfile'){if(me){me.name=String(d.username||me.name).trim();me.avatar=d.avatar||me.avatar;this.send(id,'profileData',{profile:{username:me.name,avatar:me.avatar,gamesPlayed:0,wins:0,losses:0}});this.updateList()}return}
    if(event==='getProfile'){const p=this.player(d.targetId);if(!p)return this.send(id,'profileInfoError','بازیکن یافت نشد');return this.send(id,'profileInfo',{id:p.id,name:p.name,avatar:p.avatar||'🐔',gamesPlayed:0,wins:0,losses:0})}
    if(event==='requestGame'){const target=this.player(d.targetId);if(!me||!target)return this.send(id,'gameRequestError','بازیکن مورد نظر یافت نشد');(this.pendingRequests[target.id] ||= []).push({fromId:id,fromName:me.name,timestamp:Date.now()});me.status='requesting';this.updateList();this.send(target.id,'gameRequest',{fromId:id,fromName:me.name});return}
    if(event==='rejectGame'){const target=this.player(id),req=this.player(d.fromId);if(this.pendingRequests[id])this.pendingRequests[id]=this.pendingRequests[id].filter(x=>x.fromId!==d.fromId);if(target&&target.status==='requested')target.status='ready';if(req&&req.status==='requesting')req.status='ready';this.updateList();return this.send(d.fromId,'gameRejected',{byName:target?.name||'بازیکن'})}
    if(event==='acceptGame'){const target=me,req=this.player(d.fromId);if(!target||!req)return this.send(id,'gameError','بازیکن یافت نشد');this.pendingRequests[id]=(this.pendingRequests[id]||[]).filter(x=>x.fromId!==d.fromId);const cur=this.roomFor(id);if(cur&&cur.role==='player'){return this.send(id,'busyGameChoice',{fromId:req.id,fromName:req.name,roomId:cur.roomId,message:`${req.name} می‌خواهد وارد بازی شما شود`})}target.status='playing';req.status='playing';this.updateList();const rid=this.newRoom(req,target);this.clients.get(req.id)?.send(JSON.stringify({event:'gameStarted',data:{roomId:rid}}));this.start(rid);return}
    if(event==='chooseGameOption'){const target=me,req=this.player(d.fromId);if(!target||!req)return;const cur=this.roomFor(id);if(!cur||cur.role!=='player')return this.send(id,'gameError','بازی فعلی پیدا نشد');const r=cur.room;if(d.option==='join'){if(!r.players.some(p=>p.id===req.id)){const rr=this.roomFor(req.id);if(rr&&rr.role==='player')return this.send(id,'gameError','این بازیکن خودش در یک بازی دیگر است');if(rr&&rr.role==='watcher')rr.room.watchers=rr.room.watchers.filter(x=>x!==req.id);const np={id:req.id,name:req.name,hand:[],eggs:0,chicks:0};for(let i=0;i<4&&r.deck.length;i++)np.hand.push(r.deck.pop());r.players.push(np)}req.status='playing';this.clients.get(req.id)?.send(JSON.stringify({event:'joinExistingGame',data:{roomId:cur.roomId,room:r,mode:'player'}}));this.broadcast(cur.roomId);this.emitRoom(cur.roomId,'gameNotice',{message:`👥 ${req.name} به بازی پیوست`})}else{r.watchers ||= [];if(!r.watchers.includes(req.id))r.watchers.push(req.id);req.status='watching';this.clients.get(req.id)?.send(JSON.stringify({event:'joinExistingGame',data:{roomId:cur.roomId,room:r,mode:'watcher'}}));this.broadcast(cur.roomId);this.emitRoom(cur.roomId,'gameNotice',{message:`👀 ${req.name} وارد تماشا شد`})}this.updateList();return}
    if(event==='quickGame'){if(!me)return;if(me.status!=='ready')return this.send(id,'quickGameError','ابتدا باید آماده باشید');this.quickQueue.add(id);me.status='requesting';this.updateList();this.send(id,'quickGameQueued');const ids=[...this.quickQueue].filter(x=>this.player(x)?.status==='requesting');if(ids.length>=2){const a=this.player(ids[0]),b=this.player(ids[1]);this.quickQueue.delete(a.id);this.quickQueue.delete(b.id);a.status=b.status='playing';const rid=this.newRoom(a,b);this.start(rid);this.updateList()}return}
    if(event==='createRoom'){const name=String(d.playerName||me?.name||'بازیکن');if(!me)this.onlinePlayers[id]={id,name,status:'ready',avatar:'🐔'};const rid=String(d.roomId||Math.random().toString(36).slice(2,8)).toUpperCase();this.rooms[rid]={host:id,players:[{id,name,hand:[],eggs:0,chicks:0}],gameStarted:false,deck:this.deck(),eggTokens:18,currentTurn:null,winner:null,discardPile:[],watchers:[]};this.clients.get(id)?.send(JSON.stringify({event:'roomCreated',data:{roomId:rid}}));this.broadcast(rid);return}
    if(event==='joinRoom'){const r=this.rooms[String(d.roomId||'').toUpperCase()];if(!r)return this.send(id,'roomError','اتاق پیدا نشد');if(r.players.length>=3)return this.send(id,'roomError','اتاق پر است');if(r.players.some(p=>p.id===id))return;const name=String(d.playerName||me?.name||'بازیکن');if(!me)this.onlinePlayers[id]={id,name,status:'playing',avatar:'🐔'};else me.name=name; r.players.push({id,name,hand:[],eggs:0,chicks:0});this.clients.get(id)?.send(JSON.stringify({event:'roomCreated',data:{roomId:r.roomId||d.roomId}}));this.broadcast(String(d.roomId).toUpperCase());return}
    if(event==='startGame'){const r=this.rooms[d.roomId];if(!r||r.host!==id||r.players.length<2)return;this.start(d.roomId);return}
    if(event==='getGameState'){const r=this.rooms[d.roomId];if(r)this.send(id,'gameState',r);return}
    if(event==='gameAction'){const r=this.rooms[d.roomId];if(!r||!r.gameStarted)return;const p=r.players.find(x=>x.id===id);if(!p||r.currentTurn!==id)return;let done=false;const other=(d.data?.target? r.players.find(x=>x.id===d.data.target&&x.id!==id):r.players.find(x=>x.id!==id));switch(d.action){case'lay':{let h=p.hand.indexOf('مرغ'),ro=p.hand.indexOf('خروس'),n=p.hand.indexOf('لانه');if(h>=0&&ro>=0&&n>=0&&r.eggTokens>0){[h,ro,n].sort((a,b)=>b-a).forEach(i=>p.hand.splice(i,1));p.eggs++;r.eggTokens--;done=true}break}case'hatch':{let hs=p.hand.filter(c=>c==='مرغ').length;if(hs>=2&&p.eggs>0){let rem=0;for(let i=p.hand.length-1;i>=0&&rem<2;i--)if(p.hand[i]==='مرغ'){p.hand.splice(i,1);rem++}p.eggs--;p.chicks++;done=true}break}case'fox':{let i=p.hand.indexOf('روباه');if(i>=0&&other&&other.eggs>0){p.hand.splice(i,1);let k=other.hand.filter(c=>c==='خروس').length;if(k>=2){let rem=0;for(let j=other.hand.length-1;j>=0&&rem<2;j--)if(other.hand[j]==='خروس'){other.hand.splice(j,1);rem++}}else{other.eggs--;p.eggs++}done=true}break}case'snake':{let i=p.hand.indexOf('مار');if(i>=0&&other&&other.eggs>0){p.hand.splice(i,1);let n=Math.min(other.eggs,Number(d.data?.count)||1);other.eggs-=n;r.eggTokens+=n;done=true}break}case'trap':{let i=p.hand.indexOf('تله');let c=d.data?.card;if(i>=0&&other&&c&&other.hand.includes(c)){p.hand.splice(i,1);other.hand.splice(other.hand.indexOf(c),1);done=true}break}case'draw':if(r.deck.length){p.hand.push(r.deck.pop());done=true}break;case'discard':{let c=d.data?.card,i=p.hand.indexOf(c);if(i>=0){r.discardPile.push(p.hand.splice(i,1)[0]);done=true}break}case'endTurn':done=true;break}if(done){while(p.hand.length<4&&r.deck.length)p.hand.push(r.deck.pop());if(!r.deck.length&&r.discardPile.length){r.deck=this.shuffle(r.discardPile.splice(0));}for(const x of r.players)if(x.chicks>=3)r.winner=x.id;if(!r.winner){let i=r.players.findIndex(x=>x.id===r.currentTurn);r.currentTurn=r.players[(i+1)%r.players.length].id}this.broadcast(d.roomId)}}
    if(event==='chatMessage'){const r=this.rooms[d.roomId];if(!r)return;if(!r.players.some(p=>p.id===id)&&!(r.watchers||[]).includes(id))return;const name=me?.name||'تماشاگر';this.emitRoom(d.roomId,'chatMessage',{sender:name,message:String(d.message||''),time:new Date().toLocaleTimeString()});return}
    if(event==='chatMedia'){const r=this.rooms[d.roomId];if(!r)return;if(!r.players.some(p=>p.id===id)&&!(r.watchers||[]).includes(id))return;this.emitRoom(d.roomId,'chatMedia',{sender:me?.name||'تماشاگر',kind:d.kind,content:String(d.content||''),name:d.name,mime:d.mime,size:d.size,time:new Date().toLocaleTimeString()});return}
    if(event==='rematchRequest'){const t=this.player(d.targetId);if(t)this.send(t.id,'rematchRequest',{fromId:id,fromName:me?.name||'بازیکن',roomId:d.roomId||null});return}
    if(event==='acceptRematch'){const req=this.player(d.fromId);if(!req||!me)return;const rid=this.newRoom(req,me);req.status=me.status='playing';this.start(rid);this.send(req.id,'rematchAccepted',{roomId:rid});this.updateList();return}
    if(event==='rejectRematch'){return this.send(d.fromId,'rematchRejected',{byName:me?.name||'حریف'})}
    if(event==='webrtc-offer'||event==='webrtc-answer'||event==='webrtc-ice-candidate'){const r=this.roomFor(id),to=d.to;if(r&&to&&this.roomFor(to)?.roomId===r.roomId)this.send(to,event,{from:id,[event==='webrtc-offer'?'offer':event==='webrtc-answer'?'answer':'candidate']:d[event==='webrtc-offer'?'offer':event==='webrtc-answer'?'answer':'candidate']});return}
    if(event==='leaveGame'){const r=this.rooms[d.roomId];if(r){r.players=r.players.filter(p=>p.id!==id);r.watchers=(r.watchers||[]).filter(x=>x!==id);if(!r.players.length)delete this.rooms[d.roomId];else this.broadcast(d.roomId)}if(me)me.status='ready';this.updateList();return}
  }
  disconnect(id){const me=this.player(id);for(const [k,v] of Object.entries(this.pendingRequests)){const keep=(v||[]).filter(x=>x.fromId!==id);if(keep.length)this.pendingRequests[k]=keep;else delete this.pendingRequests[k]}this.quickQueue.delete(id);delete this.onlinePlayers[id];for(const [rid,r] of Object.entries(this.rooms)){r.players=r.players.filter(p=>p.id!==id);r.watchers=(r.watchers||[]).filter(x=>x!==id);if(!r.players.length)delete this.rooms[rid];else this.broadcast(rid)}this.clients.delete(id);this.updateList()}
}
export default {async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/ws'){const id=env.LOBBY.idFromName('global');return env.LOBBY.get(id).fetch(request)}return env.ASSETS.fetch(request)}};
